// ALL POST

export const FETCH_BLOG_POST_REQUEST='FETCH_BLOG_POST_REQUEST';
export const FETCH_BLOG_POST_SUCCESS='FETCH_BLOG_POST_SUCCESS';
export const FETCH_BLOG_POST_FAILURE='FETCH_BLOG_POST_FAILURE';


//SINGLE POST

export const FETCH_SINGLE_BLOG_POST_REQUEST='FETCH_SINGLE_BLOG_POST_REQUEST';
export const FETCH_SINGLE_BLOG_POST_SUCCESS='FETCH_SINGLE_BLOG_POST_SUCCESS';
export const FETCH_SINGLE_BLOG_POST_FAILURE='FETCH_SINGLE_BLOG_POST_FAILURE';


// create blogpost

export const CREATE_BLOG_POST_REQUEST="CREATE_BLOG_POST_REQUEST";
export const CREATE_BLOG_POST_SUCCESS="CREATE_BLOG_POST_SUCCESS";
export const CREATE_BLOG_POST_FAILURE="CREATE_BLOG_POST_FAILURE";


//  Post updation 

export const UPDATION_BLOG_POST_REQUEST="UPDATION_BLOG_POST_REQUEST";
export const UPDATION_BLOG_POST_SUCCESS="UPDATION_BLOG_POST_SUCCESS";
export const UPDATION_BLOG_POST_FAILURE="UPDATION_BLOG_POST_FAILURE";


//Delete article

export const DELETE_BLOG_POST_REQUEST="DELETE_BLOG_POST_REQUEST";
export const DELETE_BLOG_POST_SUCCESS="DELETE_BLOG_POST_SUCCESS";
export const DELETE_BLOG_POST_FAILURE="DELETE_BLOG_POST_FAILURE";


