// ALL POST

export const FETCH_BLOG_POST_REQUEST='FETCH_BLOG_POST_REQUEST';
export const FETCH_BLOG_POST_SUCCESS='FETCH_BLOG_POST_SUCCESS';
export const FETCH_BLOG_POST_FAILURE='FETCH_BLOG_POST_FAILURE';


//SINGLE POST

export const FETCH_SINGLE_BLOG_POST_REQUEST='FETCH_SINGLE_BLOG_POST_REQUEST';
export const FETCH_SINGLE_BLOG_POST_SUCCESS='FETCH_SINGLE_BLOG_POST_SUCCESS';
export const FETCH_SINGLE_BLOG_POST_FAILURE='FETCH_SINGLE_BLOG_POST_FAILURE';


// create blogpost

export const CREATE_BLOG_POST_REQUEST="CREATE_BLOG_POST_REQUEST";
export const CREATE_BLOG_POST_SUCCESS="CREATE_BLOG_POST_SUCCESS";
export const CREATE_BLOG_POST_FAILURE="CREATE_BLOG_POST_FAILURE";
